import fsp from '@mna/fsp'

const createIndexHtml = async (config: { dest: string }) => {

  const { dest } = config

  // Dynamic HTML

  // Not working: Write to a file and loadURL

  // TODO: Implement Content Security Policy for HTML
  // <meta http-equiv="Content-Security-Policy" content="script-src 'self'">
  // https://electronjs.org/docs/tutorial/security#6-define-a-content-security-policy
  process.env.ELECTRON_DISABLE_SECURITY_WARNINGS = 'true'

  const html = `<!DOCTYPE html>
<!-- Generated by @mna/tron -->
<html>
  <head>
    <meta charset="utf-8">
    <title>App</title>
    ${ process.env.HOT ? '' : `<link rel="stylesheet" href="./dist/style.css" />` }
  </head>
  <body>
    <div id="root"></div>
    ${ process.env.NODE_ENV!=='development' ? '' : `<script defer src="../dll/renderer.dev.dll.js"></script>` }
    <script defer src="${
  process.env.HOT
    ? 'http://localhost:' + (process.env.PORT || 1212) + '/dist/renderer.dev.js'
    : './dist/renderer.prod.js'
}"></script>
  </body>
</html>
  `

  // try {
  //   await fsp.writeFile(dest, html)
  // } catch(e) {
  //   console.log(e)
  // }

  // The method below has issue with finding root folder for scripts and styles

  //mainWindow.loadURL(`data:text/html;charset=utf-8,${encodeURI(html)}`)
}

export default createIndexHtml
