#!/usr/bin/env node

const path = require('path')
const fs = require('fs')
const script = process.argv[2] || 'start'
const args = process.argv.slice(3)
process.argv.shift()

// TODO: Run help/install script if project is missing required files

switch (script) {
case 'build':
case 'start':
  require('./scripts/' + script)
  break
case 'babel':
case 'test':
  require('./scripts/' + script)()
  break
case 'run': {

  const cwd = process.cwd()
  // Allow relative or absolute, with optional extension
  const scriptPath = path.join(cwd, `${path.relative(cwd, args.shift())}`)

  process.argv.shift()

  try {
    require('./scripts/run')({ script: scriptPath, args })
  } catch(e) {
    console.log(e)
  }
}
  break
default:
  console.log('Unknown script "' + script + '".')
  break
}
