#!/usr/bin/env node

const path = require('path')
const fs = require('fs')
const script = process.argv[2] || 'start'
const args = process.argv.slice(3)
process.argv.shift()

switch (script) {
case 'build':
case 'start':
//case 'clean':
  require('./scripts/' + script)
  break
case 'babel':
case 'test':
  require('./scripts/' + script)()
  break
/*case 'test':
  require('./scripts/run')({ script: path.join(__dirname, 'tester', 'cli'), args })
  break*/
default: {
  const scriptPath = path.join(process.cwd(), `${script}.js`)
  if (fs.existsSync(scriptPath)) {
    require('./scripts/run')({ script: scriptPath, args })
  } else {
    console.log('Unknown script "' + script + '".')
  }
}
  break
}
